source 'https://github.com/CocoaPods/Specs.git'
pod 'AFNetworking', '~> 3.0'
pod 'AMSlideMenu'
pod 'MaterialControls', '~> 1.0.2'
xcodeproj 'bitgray-ios.xcodeproj'


target 'bitgray-ios' do

end

target 'bitgray-iosTests' do

end

target 'bitgray-iosUITests' do

end

